'*******************************************************************************
' EverEdit Syntax File
' Language:   	JScript
' Maintainer:  	www.everedit.net  
' History:
'   2012/04/11	First Version
'  **Don't modify this file!**
'*******************************************************************************
Include( ".\const.mac" )

Set js=CreateParser()

Set rJsRegion=js.DefaultRegion
Set js_creator=js

Include( ".\js_base.mac" )
